[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "firebase-admin>=6.9.0",
    "gitpython>=3.1.44",
    "openai>=1.86.0",
    "telegram>=0.0.1",
]
